// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "flange-so": [
    {
      "id": "slip-on-flange-asa-300-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "flangeOd": "95",
        "pcd": "66.7",
        "rf": "34.9",
        "thk": "14.3"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 95,
        "c": 66.7,
        "rf": 34.9,
        "bore": 22.8,
        "t": 14.3,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "slip-on-flange-asa-300-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "flangeOd": "124",
        "pcd": "88.9",
        "rf": "50.8",
        "thk": "17.5"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 124,
        "c": 88.9,
        "rf": 50.8,
        "bore": 34.9,
        "t": 17.5,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "slip-on-flange-asa-300-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "flangeOd": "165",
        "pcd": "127.0",
        "rf": "92.1",
        "thk": "22.3"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 165,
        "c": 127,
        "rf": 92.1,
        "bore": 61.8,
        "t": 22.3,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "slip-on-flange-asa-300-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "flangeOd": "255",
        "pcd": "200.0",
        "rf": "157.2",
        "thk": "30.2"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 255,
        "c": 200,
        "rf": 157.2,
        "bore": 115.8,
        "t": 30.2,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "slip-on-flange-asa-300-6-150-nb",
      "title": "6\" (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "flangeOd": "318",
        "pcd": "269.9",
        "rf": "215.9",
        "thk": "35.0"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 318,
        "c": 269.9,
        "rf": 215.9,
        "bore": 169.8,
        "t": 35,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "slip-on-flange-asa-300-8-200-nb",
      "title": "8\" (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "flangeOd": "381",
        "pcd": "330.2",
        "rf": "269.9",
        "thk": "39.7"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 381,
        "c": 330.2,
        "rf": 269.9,
        "bore": 220.6,
        "t": 39.7,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "slip-on-flange-asa-300-10-250-nb",
      "title": "10\" (250 NB)",
      "fixed": {
        "nps": "10\"",
        "dn": "250",
        "flangeOd": "445",
        "pcd": "387.4",
        "rf": "323.8",
        "thk": "46.1"
      },
      "values": {
        "x": {}
      },
      "kind": "Slip-On flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 445,
        "c": 387.4,
        "rf": 323.8,
        "bore": 274.5,
        "t": 46.1,
        "hub": false,
        "weld": false
      }
    }
  ],
  "flange-wn40": [
    {
      "id": "weld-neck-bore-sch-40-flange-asa-300-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "flangeOd": "124",
        "pcd": "88.9",
        "rf": "50.8",
        "thk": "17.5"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 40) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 124,
        "c": 88.9,
        "rf": 50.8,
        "bore": 26.6,
        "t": 17.5,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-40-flange-asa-300-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "flangeOd": "210",
        "pcd": "168.3",
        "rf": "127.0",
        "thk": "28.6"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 40) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 210,
        "c": 168.3,
        "rf": 127,
        "bore": 77.9,
        "t": 28.6,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-40-flange-asa-300-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "flangeOd": "255",
        "pcd": "200.0",
        "rf": "157.2",
        "thk": "30.2"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 40) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 255,
        "c": 200,
        "rf": 157.2,
        "bore": 102.3,
        "t": 30.2,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-40-flange-asa-300-6-150-nb",
      "title": "6\" (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "flangeOd": "318",
        "pcd": "269.9",
        "rf": "215.9",
        "thk": "35.0"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 40) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 318,
        "c": 269.9,
        "rf": 215.9,
        "bore": 154.1,
        "t": 35,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-40-flange-asa-300-8-200-nb",
      "title": "8\" (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "flangeOd": "381",
        "pcd": "330.2",
        "rf": "269.9",
        "thk": "39.7"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 40) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 381,
        "c": 330.2,
        "rf": 269.9,
        "bore": 202.7,
        "t": 39.7,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-40-flange-asa-300-10-250-nb",
      "title": "10\" (250 NB)",
      "fixed": {
        "nps": "10\"",
        "dn": "250",
        "flangeOd": "445",
        "pcd": "387.4",
        "rf": "323.8",
        "thk": "46.1"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 40) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 445,
        "c": 387.4,
        "rf": 323.8,
        "bore": 254.5,
        "t": 46.1,
        "hub": true,
        "weld": true
      }
    }
  ],
  "flange-wn80": [
    {
      "id": "weld-neck-bore-sch-80-flange-asa-300-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "flangeOd": "124",
        "pcd": "88.9",
        "rf": "50.8",
        "thk": "17.5"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 80) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 124,
        "c": 88.9,
        "rf": 50.8,
        "bore": 24.3,
        "t": 17.5,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-80-flange-asa-300-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "flangeOd": "255",
        "pcd": "200.0",
        "rf": "157.2",
        "thk": "30.2"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 80) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 255,
        "c": 200,
        "rf": 157.2,
        "bore": 97.2,
        "t": 30.2,
        "hub": true,
        "weld": true
      }
    },
    {
      "id": "weld-neck-bore-sch-80-flange-asa-300-8-200-nb",
      "title": "8\" (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "flangeOd": "381",
        "pcd": "330.2",
        "rf": "269.9",
        "thk": "39.7"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 80) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 381,
        "c": 330.2,
        "rf": 269.9,
        "bore": 193.7,
        "t": 39.7,
        "hub": true,
        "weld": true
      }
    }
  ],
  "flange-wn160": [
    {
      "id": "weld-neck-bore-sch-160-flange-asa-300-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "flangeOd": "165",
        "pcd": "127.0",
        "rf": "92.1",
        "thk": "22.3"
      },
      "values": {
        "x": {}
      },
      "kind": "Weld Neck (bore Sch 160) flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 165,
        "c": 127,
        "rf": 92.1,
        "bore": 44.8,
        "t": 22.3,
        "hub": true,
        "weld": true
      }
    }
  ],
  "flange-bld": [
    {
      "id": "blind-flange-asa-300-6-150-nb",
      "title": "6\" (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "flangeOd": "318",
        "pcd": "269.9",
        "rf": "215.9",
        "thk": "35.0"
      },
      "values": {
        "x": {}
      },
      "kind": "Blind flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 318,
        "c": 269.9,
        "rf": 215.9,
        "bore": 0,
        "t": 35,
        "hub": false,
        "weld": false
      }
    },
    {
      "id": "blind-flange-asa-300-8-200-nb",
      "title": "8\" (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "flangeOd": "381",
        "pcd": "330.2",
        "rf": "269.9",
        "thk": "39.7"
      },
      "values": {
        "x": {}
      },
      "kind": "Blind flange, ASA 300",
      "drawing": {
        "kind": "flange",
        "d": 381,
        "c": 330.2,
        "rf": 269.9,
        "bore": 0,
        "t": 39.7,
        "hub": false,
        "weld": false
      }
    }
  ]
}
