// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "ms-sheet": [
    {
      "id": "1-8-ms-pipe-6-nb",
      "title": "1/8\" MS pipe (6 NB)",
      "fixed": {
        "nps": "1/8\"",
        "dn": "6",
        "od": "10.30"
      },
      "values": {
        "sch40": {
          "t": "1.73",
          "id": "6.84",
          "m": "0.36"
        },
        "sch80": {
          "t": "2.41",
          "id": "5.48",
          "m": "0.46"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 10.3
      }
    },
    {
      "id": "1-4-ms-pipe-8-nb",
      "title": "1/4\" MS pipe (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "od": "13.70"
      },
      "values": {
        "sch40": {
          "t": "2.24",
          "id": "9.22",
          "m": "0.63"
        },
        "sch80": {
          "t": "3.02",
          "id": "7.66",
          "m": "0.80"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 13.7
      }
    },
    {
      "id": "3-8-ms-pipe-10-nb",
      "title": "3/8\" MS pipe (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "od": "17.10"
      },
      "values": {
        "sch40": {
          "t": "2.31",
          "id": "12.48",
          "m": "0.85"
        },
        "sch80": {
          "t": "3.20",
          "id": "10.70",
          "m": "1.10"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 17.1
      }
    },
    {
      "id": "1-2-ms-pipe-15-nb",
      "title": "1/2\" MS pipe (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "od": "21.30"
      },
      "values": {
        "sch40": {
          "t": "2.77",
          "id": "15.76",
          "m": "1.27"
        },
        "sch80": {
          "t": "3.73",
          "id": "13.84",
          "m": "1.62"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 21.3
      }
    },
    {
      "id": "3-4-ms-pipe-20-nb",
      "title": "3/4\" MS pipe (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "od": "26.70"
      },
      "values": {
        "sch40": {
          "t": "2.87",
          "id": "20.96",
          "m": "1.68"
        },
        "sch80": {
          "t": "3.91",
          "id": "18.88",
          "m": "2.19"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 26.7
      }
    },
    {
      "id": "1-ms-pipe-25-nb",
      "title": "1\" MS pipe (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "od": "33.40"
      },
      "values": {
        "sch40": {
          "t": "3.38",
          "id": "26.64",
          "m": "2.50"
        },
        "sch80": {
          "t": "4.55",
          "id": "24.30",
          "m": "3.23"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 33.4
      }
    },
    {
      "id": "1-1-4-ms-pipe-32-nb",
      "title": "1 1/4\" MS pipe (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "od": "42.20"
      },
      "values": {
        "sch40": {
          "t": "3.56",
          "id": "35.08",
          "m": "3.38"
        },
        "sch80": {
          "t": "4.85",
          "id": "32.50",
          "m": "4.46"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 42.2
      }
    },
    {
      "id": "1-1-2-ms-pipe-40-nb",
      "title": "1 1/2\" MS pipe (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "od": "48.30"
      },
      "values": {
        "sch40": {
          "t": "3.68",
          "id": "40.94",
          "m": "4.05"
        },
        "sch80": {
          "t": "5.08",
          "id": "38.14",
          "m": "5.40"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 48.3
      }
    },
    {
      "id": "2-ms-pipe-50-nb",
      "title": "2\" MS pipe (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "od": "60.30"
      },
      "values": {
        "sch40": {
          "t": "3.91",
          "id": "52.48",
          "m": "5.43"
        },
        "sch80": {
          "t": "5.54",
          "id": "49.22",
          "m": "7.49"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 60.3
      }
    },
    {
      "id": "2-1-2-ms-pipe-65-nb",
      "title": "2 1/2\" MS pipe (65 NB)",
      "fixed": {
        "nps": "2 1/2\"",
        "dn": "65",
        "od": "73.00"
      },
      "values": {
        "sch40": {
          "t": "5.16",
          "id": "62.68",
          "m": "8.62"
        },
        "sch80": {
          "t": "7.01",
          "id": "58.98",
          "m": "11.40"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 73
      }
    },
    {
      "id": "3-ms-pipe-80-nb",
      "title": "3\" MS pipe (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "od": "88.90"
      },
      "values": {
        "sch40": {
          "t": "5.49",
          "id": "77.92",
          "m": "11.29"
        },
        "sch80": {
          "t": "7.62",
          "id": "73.66",
          "m": "15.25"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 88.9
      }
    },
    {
      "id": "3-1-2-ms-pipe-90-nb",
      "title": "3 1/2\" MS pipe (90 NB)",
      "fixed": {
        "nps": "3 1/2\"",
        "dn": "90",
        "od": "101.60"
      },
      "values": {
        "sch40": {
          "t": "5.74",
          "id": "90.12",
          "m": "13.57"
        },
        "sch80": {
          "t": "8.08",
          "id": "85.44",
          "m": "18.62"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 101.6
      }
    },
    {
      "id": "4-ms-pipe-100-nb",
      "title": "4\" MS pipe (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "od": "114.30"
      },
      "values": {
        "sch40": {
          "t": "6.02",
          "id": "102.26",
          "m": "16.07"
        },
        "sch80": {
          "t": "8.56",
          "id": "97.18",
          "m": "22.31"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 114.3
      }
    },
    {
      "id": "5-ms-pipe-125-nb",
      "title": "5\" MS pipe (125 NB)",
      "fixed": {
        "nps": "5\"",
        "dn": "125",
        "od": "141.30"
      },
      "values": {
        "sch40": {
          "t": "6.55",
          "id": "128.20",
          "m": "21.78"
        },
        "sch80": {
          "t": "9.52",
          "id": "122.26",
          "m": "30.92"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 141.3
      }
    },
    {
      "id": "6-ms-pipe-150-nb",
      "title": "6\" MS pipe (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "od": "168.30"
      },
      "values": {
        "sch40": {
          "t": "7.11",
          "id": "154.08",
          "m": "28.26"
        },
        "sch80": {
          "t": "10.97",
          "id": "146.36",
          "m": "42.56"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 168.3
      }
    },
    {
      "id": "8-ms-pipe-200-nb",
      "title": "8\" MS pipe (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "od": "219.10"
      },
      "values": {
        "sch40": {
          "t": "8.18",
          "id": "202.74",
          "m": "42.53"
        },
        "sch80": {
          "t": "12.70",
          "id": "193.70",
          "m": "64.63"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 219.1
      }
    },
    {
      "id": "10-ms-pipe-250-nb",
      "title": "10\" MS pipe (250 NB)",
      "fixed": {
        "nps": "10\"",
        "dn": "250",
        "od": "273.00"
      },
      "values": {
        "sch40": {
          "t": "9.27",
          "id": "254.46",
          "m": "60.29"
        },
        "sch80": {
          "t": "15.06",
          "id": "242.88",
          "m": "95.90"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 273
      }
    },
    {
      "id": "12-ms-pipe-300-nb",
      "title": "12\" MS pipe (300 NB)",
      "fixed": {
        "nps": "12\"",
        "dn": "300",
        "od": "323.80"
      },
      "values": {
        "sch40": {
          "t": "10.31",
          "id": "303.18",
          "m": "79.72"
        },
        "sch80": {
          "t": "17.35",
          "id": "289.10",
          "m": "131.89"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 323.8
      }
    },
    {
      "id": "14-ms-pipe-350-nb",
      "title": "14\" MS pipe (350 NB)",
      "fixed": {
        "nps": "14\"",
        "dn": "350",
        "od": "355.60"
      },
      "values": {
        "sch40": {
          "t": "11.13",
          "id": "333.34",
          "m": "94.40"
        },
        "sch80": {
          "t": "19.05",
          "id": "317.50",
          "m": "157.95"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 355.6
      }
    },
    {
      "id": "16-ms-pipe-400-nb",
      "title": "16\" MS pipe (400 NB)",
      "fixed": {
        "nps": "16\"",
        "dn": "400",
        "od": "406.40"
      },
      "values": {
        "sch40": {
          "t": "12.70",
          "id": "381.00",
          "m": "123.29"
        },
        "sch80": {
          "t": "21.41",
          "id": "363.58",
          "m": "203.32"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 406.4
      }
    },
    {
      "id": "18-ms-pipe-450-nb",
      "title": "18\" MS pipe (450 NB)",
      "fixed": {
        "nps": "18\"",
        "dn": "450",
        "od": "457.20"
      },
      "values": {
        "sch40": {
          "t": "14.27",
          "id": "428.66",
          "m": "155.91"
        },
        "sch80": {
          "t": "23.80",
          "id": "409.60",
          "m": "254.38"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 457.2
      }
    },
    {
      "id": "20-ms-pipe-500-nb",
      "title": "20\" MS pipe (500 NB)",
      "fixed": {
        "nps": "20\"",
        "dn": "500",
        "od": "508.00"
      },
      "values": {
        "sch40": {
          "t": "15.06",
          "id": "477.88",
          "m": "183.15"
        },
        "sch80": {
          "t": "26.19",
          "id": "455.62",
          "m": "310.82"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 508
      }
    },
    {
      "id": "22-ms-pipe-550-nb",
      "title": "22\" MS pipe (550 NB)",
      "fixed": {
        "nps": "22\"",
        "dn": "550",
        "od": "558.80"
      },
      "values": {
        "sch80": {
          "t": "28.58",
          "id": "501.64",
          "m": "373.83"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 558.8
      }
    },
    {
      "id": "24-ms-pipe-600-nb",
      "title": "24\" MS pipe (600 NB)",
      "fixed": {
        "nps": "24\"",
        "dn": "600",
        "od": "609.60"
      },
      "values": {
        "sch40": {
          "t": "17.35",
          "id": "574.90",
          "m": "254.93"
        },
        "sch80": {
          "t": "30.94",
          "id": "547.72",
          "m": "441.90"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 609.6
      }
    }
  ]
}
