// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "sans62-sheet": [
    {
      "id": "1-2-sans-62-pipe-15-nb",
      "title": "1/2\" SANS 62 pipe (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "od": "21.30"
      },
      "values": {
        "med": {
          "t": "2.65",
          "id": "16.0",
          "m": "1.22"
        },
        "hvy": {
          "t": "3.25",
          "id": "14.8",
          "m": "1.45"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 21.3
      }
    },
    {
      "id": "3-4-sans-62-pipe-20-nb",
      "title": "3/4\" SANS 62 pipe (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "od": "26.90"
      },
      "values": {
        "med": {
          "t": "2.65",
          "id": "21.6",
          "m": "1.58"
        },
        "hvy": {
          "t": "3.25",
          "id": "20.4",
          "m": "1.90"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 26.9
      }
    },
    {
      "id": "1-sans-62-pipe-25-nb",
      "title": "1\" SANS 62 pipe (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "od": "33.70"
      },
      "values": {
        "med": {
          "t": "3.25",
          "id": "27.2",
          "m": "2.44"
        },
        "hvy": {
          "t": "4.05",
          "id": "25.6",
          "m": "2.96"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 33.7
      }
    },
    {
      "id": "1-1-4-sans-62-pipe-32-nb",
      "title": "1 1/4\" SANS 62 pipe (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "od": "42.40"
      },
      "values": {
        "med": {
          "t": "3.25",
          "id": "35.9",
          "m": "3.14"
        },
        "hvy": {
          "t": "4.05",
          "id": "34.3",
          "m": "3.83"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 42.4
      }
    },
    {
      "id": "1-1-2-sans-62-pipe-40-nb",
      "title": "1 1/2\" SANS 62 pipe (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "od": "48.30"
      },
      "values": {
        "med": {
          "t": "3.25",
          "id": "41.8",
          "m": "3.61"
        },
        "hvy": {
          "t": "4.05",
          "id": "40.2",
          "m": "4.42"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 48.3
      }
    },
    {
      "id": "2-sans-62-pipe-50-nb",
      "title": "2\" SANS 62 pipe (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "od": "60.30"
      },
      "values": {
        "med": {
          "t": "3.65",
          "id": "53.0",
          "m": "5.10"
        },
        "hvy": {
          "t": "4.50",
          "id": "51.3",
          "m": "6.19"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 60.3
      }
    },
    {
      "id": "2-1-2-sans-62-pipe-65-nb",
      "title": "2 1/2\" SANS 62 pipe (65 NB)",
      "fixed": {
        "nps": "2 1/2\"",
        "dn": "65",
        "od": "76.10"
      },
      "values": {
        "med": {
          "t": "3.65",
          "id": "68.8",
          "m": "6.52"
        },
        "hvy": {
          "t": "4.50",
          "id": "67.1",
          "m": "7.95"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 76.1
      }
    },
    {
      "id": "3-sans-62-pipe-80-nb",
      "title": "3\" SANS 62 pipe (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "od": "88.90"
      },
      "values": {
        "med": {
          "t": "4.05",
          "id": "80.8",
          "m": "8.47"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 88.9
      }
    },
    {
      "id": "4-sans-62-pipe-100-nb",
      "title": "4\" SANS 62 pipe (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "od": "114.30"
      },
      "values": {
        "med": {
          "t": "4.50",
          "id": "105.3",
          "m": "12.18"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 114.3
      }
    },
    {
      "id": "5-sans-62-pipe-125-nb",
      "title": "5\" SANS 62 pipe (125 NB)",
      "fixed": {
        "nps": "5\"",
        "dn": "125",
        "od": "139.70"
      },
      "values": {
        "med": {
          "t": "4.85",
          "id": "130.0",
          "m": "16.13"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 139.7
      }
    },
    {
      "id": "6-sans-62-pipe-150-nb",
      "title": "6\" SANS 62 pipe (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "od": "165.10"
      },
      "values": {
        "med": {
          "t": "4.85",
          "id": "155.4",
          "m": "19.17"
        },
        "hvy": {
          "t": "5.40",
          "id": "154.3",
          "m": "21.27"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 165.1
      }
    }
  ]
}
