// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "sans719-sheet": [
    {
      "id": "8-sans-719-gr-a-pipe-200-nb",
      "title": "8\" SANS 719 Gr A pipe (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "od": "219.10",
        "grade": "Gr A"
      },
      "values": {
        "x": {
          "t": "3.50",
          "id": "212.1",
          "m": "18.61"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 219.1
      }
    },
    {
      "id": "8-sans-719-gr-a-pipe-200-nb-2",
      "title": "8\" SANS 719 Gr A pipe (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "od": "219.10",
        "grade": "Gr A"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "210.1",
          "m": "23.81"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 219.1
      }
    },
    {
      "id": "8-sans-719-gr-a-pipe-200-nb-3",
      "title": "8\" SANS 719 Gr A pipe (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "od": "219.10",
        "grade": "Gr A"
      },
      "values": {
        "x": {
          "t": "6.00",
          "id": "207.1",
          "m": "31.53"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 219.1
      }
    },
    {
      "id": "10-sans-719-gr-b-pipe-250-nb",
      "title": "10\" SANS 719 Gr B pipe (250 NB)",
      "fixed": {
        "nps": "10\"",
        "dn": "250",
        "od": "273.00",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "264.0",
          "m": "29.80"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 273
      }
    },
    {
      "id": "10-sans-719-gr-b-pipe-250-nb-2",
      "title": "10\" SANS 719 Gr B pipe (250 NB)",
      "fixed": {
        "nps": "10\"",
        "dn": "250",
        "od": "273.00",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "6.00",
          "id": "261.0",
          "m": "39.51"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 273
      }
    },
    {
      "id": "12-sans-719-gr-b-pipe-300-nb",
      "title": "12\" SANS 719 Gr B pipe (300 NB)",
      "fixed": {
        "nps": "12\"",
        "dn": "300",
        "od": "323.90",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "314.9",
          "m": "35.44"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 323.9
      }
    },
    {
      "id": "12-sans-719-gr-b-pipe-300-nb-2",
      "title": "12\" SANS 719 Gr B pipe (300 NB)",
      "fixed": {
        "nps": "12\"",
        "dn": "300",
        "od": "323.90",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "6.00",
          "id": "311.9",
          "m": "47.04"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 323.9
      }
    },
    {
      "id": "14-sans-719-gr-b-pipe-350-nb",
      "title": "14\" SANS 719 Gr B pipe (350 NB)",
      "fixed": {
        "nps": "14\"",
        "dn": "350",
        "od": "355.60",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "346.6",
          "m": "38.96"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 355.6
      }
    },
    {
      "id": "14-sans-719-gr-b-pipe-350-nb-2",
      "title": "14\" SANS 719 Gr B pipe (350 NB)",
      "fixed": {
        "nps": "14\"",
        "dn": "350",
        "od": "355.60",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "6.00",
          "id": "343.6",
          "m": "51.73"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 355.6
      }
    },
    {
      "id": "16-sans-719-gr-b-pipe-400-nb",
      "title": "16\" SANS 719 Gr B pipe (400 NB)",
      "fixed": {
        "nps": "16\"",
        "dn": "400",
        "od": "406.40",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "397.4",
          "m": "44.60"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 406.4
      }
    },
    {
      "id": "16-sans-719-gr-b-pipe-400-nb-2",
      "title": "16\" SANS 719 Gr B pipe (400 NB)",
      "fixed": {
        "nps": "16\"",
        "dn": "400",
        "od": "406.40",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "6.00",
          "id": "394.4",
          "m": "59.24"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 406.4
      }
    },
    {
      "id": "18-sans-719-gr-b-pipe-450-nb",
      "title": "18\" SANS 719 Gr B pipe (450 NB)",
      "fixed": {
        "nps": "18\"",
        "dn": "450",
        "od": "457.00",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "448.0",
          "m": "50.21"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 457
      }
    },
    {
      "id": "20-sans-719-gr-b-pipe-500-nb",
      "title": "20\" SANS 719 Gr B pipe (500 NB)",
      "fixed": {
        "nps": "20\"",
        "dn": "500",
        "od": "508.00",
        "grade": "Gr B"
      },
      "values": {
        "x": {
          "t": "4.50",
          "id": "499.0",
          "m": "55.87"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 508
      }
    }
  ]
}
