// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "ss-elbow-90": [
    {
      "id": "elbow-90-lr-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "od": "21.34",
        "ctr": "38.10"
      },
      "values": {
        "ss10": {
          "id": "17.12",
          "t": "2.11"
        },
        "ss40": {
          "id": "15.80",
          "t": "2.77"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 21.34,
        "centreToEnd": 38.1,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "od": "26.67",
        "ctr": "28.60"
      },
      "values": {
        "ss10": {
          "id": "22.45",
          "t": "2.11"
        },
        "ss40": {
          "id": "20.93",
          "t": "2.87"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 26.67,
        "centreToEnd": 28.6,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "od": "33.40",
        "ctr": "38.10"
      },
      "values": {
        "ss10": {
          "id": "27.86",
          "t": "2.77"
        },
        "ss40": {
          "id": "26.64",
          "t": "3.38"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 33.4,
        "centreToEnd": 38.1,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "od": "42.16",
        "ctr": "47.60"
      },
      "values": {
        "ss10": {
          "id": "36.62",
          "t": "2.77"
        },
        "ss40": {
          "id": "35.04",
          "t": "3.56"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 42.16,
        "centreToEnd": 47.6,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "od": "48.26",
        "ctr": "57.20"
      },
      "values": {
        "ss10": {
          "id": "42.72",
          "t": "2.77"
        },
        "ss40": {
          "id": "40.90",
          "t": "3.68"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 48.26,
        "centreToEnd": 57.2,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "od": "60.33",
        "ctr": "76.20"
      },
      "values": {
        "ss10": {
          "id": "54.79",
          "t": "2.77"
        },
        "ss40": {
          "id": "52.51",
          "t": "3.91"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 60.33,
        "centreToEnd": 76.2,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-2-1-2-65-nb",
      "title": "2 1/2\" (65 NB)",
      "fixed": {
        "nps": "2 1/2\"",
        "dn": "65",
        "od": "73.03",
        "ctr": "95.30"
      },
      "values": {
        "ss10": {
          "id": "66.93",
          "t": "3.05"
        },
        "ss40": {
          "id": "62.71",
          "t": "5.16"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 73.03,
        "centreToEnd": 95.3,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "od": "88.90",
        "ctr": "114.30"
      },
      "values": {
        "ss10": {
          "id": "82.80",
          "t": "3.05"
        },
        "ss40": {
          "id": "77.92",
          "t": "5.49"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 88.9,
        "centreToEnd": 114.3,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "od": "114.30",
        "ctr": "152.40"
      },
      "values": {
        "ss10": {
          "id": "108.20",
          "t": "3.05"
        },
        "ss40": {
          "id": "102.26",
          "t": "6.02"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 114.3,
        "centreToEnd": 152.4,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-6-150-nb",
      "title": "6\" (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "od": "168.28",
        "ctr": "228.60"
      },
      "values": {
        "ss10": {
          "id": "161.48",
          "t": "3.40"
        },
        "ss40": {
          "id": "154.06",
          "t": "7.11"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 168.28,
        "centreToEnd": 228.6,
        "angle": 90,
        "centreLabel": "A"
      }
    },
    {
      "id": "elbow-90-lr-8-200-nb",
      "title": "8\" (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "od": "219.08",
        "ctr": "304.80"
      },
      "values": {
        "ss10": {
          "id": "211.56",
          "t": "3.76"
        },
        "ss40": {
          "id": "202.72",
          "t": "8.18"
        }
      },
      "kind": "Elbow 90° LR",
      "drawing": {
        "kind": "elbow",
        "od": 219.08,
        "centreToEnd": 304.8,
        "angle": 90,
        "centreLabel": "A"
      }
    }
  ],
  "ss-tee": [
    {
      "id": "equal-tee-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "od": "21.34",
        "a": "25.40",
        "b": "25.40"
      },
      "values": {
        "ss10": {
          "id": "17.12,17.12",
          "t": "2.11,2.11"
        },
        "ss40": {
          "id": "15.80,15.80",
          "t": "2.77,2.77"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          21.34,
          21.34
        ],
        "a": 25.4,
        "b": 25.4
      }
    },
    {
      "id": "equal-tee-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "od": "26.67",
        "a": "28.60",
        "b": "28.60"
      },
      "values": {
        "ss10": {
          "id": "22.45,22.45",
          "t": "2.11,2.11"
        },
        "ss40": {
          "id": "20.93,20.93",
          "t": "2.87,2.87"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          26.67,
          26.67
        ],
        "a": 28.6,
        "b": 28.6
      }
    },
    {
      "id": "equal-tee-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "od": "33.40",
        "a": "38.10",
        "b": "38.10"
      },
      "values": {
        "ss10": {
          "id": "27.86,27.86",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "26.64,26.64",
          "t": "3.38,3.38"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          33.4,
          33.4
        ],
        "a": 38.1,
        "b": 38.1
      }
    },
    {
      "id": "equal-tee-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "od": "42.16",
        "a": "47.60",
        "b": "47.60"
      },
      "values": {
        "ss10": {
          "id": "36.62,36.62",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "35.04,35.04",
          "t": "3.56,3.56"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          42.16,
          42.16
        ],
        "a": 47.6,
        "b": 47.6
      }
    },
    {
      "id": "equal-tee-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "od": "48.26",
        "a": "57.10",
        "b": "57.10"
      },
      "values": {
        "ss10": {
          "id": "42.72,42.72",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "40.90,40.90",
          "t": "3.68,3.68"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          48.26,
          48.26
        ],
        "a": 57.1,
        "b": 57.1
      }
    },
    {
      "id": "equal-tee-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "od": "60.33",
        "a": "63.50",
        "b": "63.50"
      },
      "values": {
        "ss10": {
          "id": "54.79,54.79",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "52.51,52.51",
          "t": "3.91,3.91"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          60.33,
          60.33
        ],
        "a": 63.5,
        "b": 63.5
      }
    },
    {
      "id": "equal-tee-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "od": "88.90",
        "a": "85.70",
        "b": "85.70"
      },
      "values": {
        "ss10": {
          "id": "82.80,82.80",
          "t": "3.05,3.05"
        },
        "ss40": {
          "id": "77.92,77.92",
          "t": "5.49,5.49"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          88.9,
          88.9
        ],
        "a": 85.7,
        "b": 85.7
      }
    },
    {
      "id": "equal-tee-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "od": "114.30",
        "a": "104.80",
        "b": "104.80"
      },
      "values": {
        "ss10": {
          "id": "108.20,108.20",
          "t": "3.05,3.05"
        },
        "ss40": {
          "id": "102.26,102.26",
          "t": "6.02,6.02"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          114.3,
          114.3
        ],
        "a": 104.8,
        "b": 104.8
      }
    },
    {
      "id": "equal-tee-6-150-nb",
      "title": "6\" (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "od": "168.28",
        "a": "142.90",
        "b": "142.90"
      },
      "values": {
        "ss10": {
          "id": "161.48,161.48",
          "t": "3.40,3.40"
        },
        "ss40": {
          "id": "154.06,154.06",
          "t": "7.11,7.11"
        }
      },
      "kind": "Equal tee",
      "drawing": {
        "kind": "tee",
        "od": [
          168.28,
          168.28
        ],
        "a": 142.9,
        "b": 142.9
      }
    }
  ],
  "ss-reducer": [
    {
      "id": "concentric-reducer-1-x-1-2-25-x-15-nb",
      "title": "1\" x 1/2\" (25 x 15 NB)",
      "fixed": {
        "nps": "1\" x 1/2\"",
        "dn": "25 x 15",
        "od": "33.40 / 21.34",
        "len": "50.80"
      },
      "values": {
        "ss10": {
          "id": "27.86,17.12",
          "t": "2.77,2.11"
        },
        "ss40": {
          "id": "26.64,15.80",
          "t": "3.38,2.77"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          33.4,
          21.34
        ],
        "length": 50.8,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-1-x-3-4-25-x-20-nb",
      "title": "1\" x 3/4\" (25 x 20 NB)",
      "fixed": {
        "nps": "1\" x 3/4\"",
        "dn": "25 x 20",
        "od": "33.40 / 26.67",
        "len": "50.80"
      },
      "values": {
        "ss10": {
          "id": "27.86,22.45",
          "t": "2.77,2.11"
        },
        "ss40": {
          "id": "26.64,20.93",
          "t": "3.38,2.87"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          33.4,
          26.67
        ],
        "length": 50.8,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-1-1-2-x-1-40-x-25-nb",
      "title": "1 1/2\" x 1\" (40 x 25 NB)",
      "fixed": {
        "nps": "1 1/2\" x 1\"",
        "dn": "40 x 25",
        "od": "48.26 / 33.40",
        "len": "63.50"
      },
      "values": {
        "ss10": {
          "id": "42.72,27.86",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "40.90,26.64",
          "t": "3.68,3.38"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          48.26,
          33.4
        ],
        "length": 63.5,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-2-x-1-50-x-25-nb",
      "title": "2\" x 1\" (50 x 25 NB)",
      "fixed": {
        "nps": "2\" x 1\"",
        "dn": "50 x 25",
        "od": "60.33 / 33.40",
        "len": "72.20"
      },
      "values": {
        "ss10": {
          "id": "54.79,27.86",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "52.51,26.64",
          "t": "3.91,3.38"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          60.33,
          33.4
        ],
        "length": 72.2,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-2-x-1-1-4-50-x-32-nb",
      "title": "2\" x 1 1/4\" (50 x 32 NB)",
      "fixed": {
        "nps": "2\" x 1 1/4\"",
        "dn": "50 x 32",
        "od": "60.33 / 42.16",
        "len": "72.20"
      },
      "values": {
        "ss10": {
          "id": "54.79,36.62",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "52.51,35.04",
          "t": "3.91,3.56"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          60.33,
          42.16
        ],
        "length": 72.2,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-2-x-1-1-2-50-x-40-nb",
      "title": "2\" x 1 1/2\" (50 x 40 NB)",
      "fixed": {
        "nps": "2\" x 1 1/2\"",
        "dn": "50 x 40",
        "od": "60.33 / 48.26",
        "len": "72.20"
      },
      "values": {
        "ss10": {
          "id": "54.79,42.72",
          "t": "2.77,2.77"
        },
        "ss40": {
          "id": "52.51,40.90",
          "t": "3.91,3.68"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          60.33,
          48.26
        ],
        "length": 72.2,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-2-1-2-x-2-65-x-50-nb",
      "title": "2 1/2\" x 2\" (65 x 50 NB)",
      "fixed": {
        "nps": "2 1/2\" x 2\"",
        "dn": "65 x 50",
        "od": "73.03 / 60.33",
        "len": "88.90"
      },
      "values": {
        "ss10": {
          "id": "66.93,54.79",
          "t": "3.05,2.77"
        },
        "ss40": {
          "id": "62.71,52.51",
          "t": "5.16,3.91"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          73.03,
          60.33
        ],
        "length": 88.9,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-3-x-1-1-2-80-x-40-nb",
      "title": "3\" x 1 1/2\" (80 x 40 NB)",
      "fixed": {
        "nps": "3\" x 1 1/2\"",
        "dn": "80 x 40",
        "od": "88.90 / 48.26",
        "len": "88.90"
      },
      "values": {
        "ss10": {
          "id": "82.80,42.72",
          "t": "3.05,2.77"
        },
        "ss40": {
          "id": "77.92,40.90",
          "t": "5.49,3.68"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          88.9,
          48.26
        ],
        "length": 88.9,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-3-x-2-80-x-50-nb",
      "title": "3\" x 2\" (80 x 50 NB)",
      "fixed": {
        "nps": "3\" x 2\"",
        "dn": "80 x 50",
        "od": "88.90 / 60.33",
        "len": "88.90"
      },
      "values": {
        "ss10": {
          "id": "82.80,54.79",
          "t": "3.05,2.77"
        },
        "ss40": {
          "id": "77.92,52.51",
          "t": "5.49,3.91"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          88.9,
          60.33
        ],
        "length": 88.9,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-4-x-2-100-x-50-nb",
      "title": "4\" x 2\" (100 x 50 NB)",
      "fixed": {
        "nps": "4\" x 2\"",
        "dn": "100 x 50",
        "od": "114.30 / 60.33",
        "len": "101.60"
      },
      "values": {
        "ss10": {
          "id": "108.20,54.79",
          "t": "3.05,2.77"
        },
        "ss40": {
          "id": "102.26,52.51",
          "t": "6.02,3.91"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          114.3,
          60.33
        ],
        "length": 101.6,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-4-x-3-100-x-80-nb",
      "title": "4\" x 3\" (100 x 80 NB)",
      "fixed": {
        "nps": "4\" x 3\"",
        "dn": "100 x 80",
        "od": "114.30 / 88.90",
        "len": "101.60"
      },
      "values": {
        "ss10": {
          "id": "108.20,82.80",
          "t": "3.05,3.05"
        },
        "ss40": {
          "id": "102.26,77.92",
          "t": "6.02,5.49"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          114.3,
          88.9
        ],
        "length": 101.6,
        "eccentric": false
      }
    },
    {
      "id": "concentric-reducer-6-x-4-150-x-100-nb",
      "title": "6\" x 4\" (150 x 100 NB)",
      "fixed": {
        "nps": "6\" x 4\"",
        "dn": "150 x 100",
        "od": "168.28 / 114.30",
        "len": "139.70"
      },
      "values": {
        "ss10": {
          "id": "161.48,108.20",
          "t": "3.40,3.05"
        },
        "ss40": {
          "id": "154.06,102.26",
          "t": "7.11,6.02"
        }
      },
      "kind": "Concentric reducer",
      "drawing": {
        "kind": "reducer",
        "od": [
          168.28,
          114.3
        ],
        "length": 139.7,
        "eccentric": false
      }
    }
  ]
}
