// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "ss-sheet": [
    {
      "id": "1-2-ss-pipe-15-nb",
      "title": "1/2\" SS pipe (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "od": "21.34"
      },
      "values": {
        "sch10s": {
          "t": "2.11",
          "id": "17.12",
          "m": "1.02"
        },
        "sch40s": {
          "t": "2.77",
          "id": "15.80",
          "m": "1.26"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 21.34
      }
    },
    {
      "id": "3-4-ss-pipe-20-nb",
      "title": "3/4\" SS pipe (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "od": "26.67"
      },
      "values": {
        "sch10s": {
          "t": "2.11",
          "id": "22.45",
          "m": "1.30"
        },
        "sch40s": {
          "t": "2.87",
          "id": "20.93",
          "m": "1.68"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 26.67
      }
    },
    {
      "id": "1-ss-pipe-25-nb",
      "title": "1\" SS pipe (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "od": "33.40"
      },
      "values": {
        "sch10s": {
          "t": "2.77",
          "id": "27.86",
          "m": "2.13"
        },
        "sch40s": {
          "t": "3.38",
          "id": "26.64",
          "m": "2.50"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 33.4
      }
    },
    {
      "id": "1-1-4-ss-pipe-32-nb",
      "title": "1 1/4\" SS pipe (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "od": "42.16"
      },
      "values": {
        "sch10s": {
          "t": "2.77",
          "id": "36.62",
          "m": "2.73"
        },
        "sch40s": {
          "t": "3.56",
          "id": "35.04",
          "m": "3.38"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 42.16
      }
    },
    {
      "id": "1-1-2-ss-pipe-40-nb",
      "title": "1 1/2\" SS pipe (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "od": "48.26"
      },
      "values": {
        "sch10s": {
          "t": "2.77",
          "id": "42.72",
          "m": "3.16"
        },
        "sch40s": {
          "t": "3.68",
          "id": "40.90",
          "m": "4.05"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 48.26
      }
    },
    {
      "id": "2-ss-pipe-50-nb",
      "title": "2\" SS pipe (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "od": "60.33"
      },
      "values": {
        "sch10s": {
          "t": "2.77",
          "id": "54.79",
          "m": "3.99"
        },
        "sch40s": {
          "t": "3.91",
          "id": "52.51",
          "m": "5.43"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 60.33
      }
    },
    {
      "id": "2-1-2-ss-pipe-65-nb",
      "title": "2 1/2\" SS pipe (65 NB)",
      "fixed": {
        "nps": "2 1/2\"",
        "dn": "65",
        "od": "73.03"
      },
      "values": {
        "sch10s": {
          "t": "3.05",
          "id": "66.93",
          "m": "5.35"
        },
        "sch40s": {
          "t": "5.16",
          "id": "62.71",
          "m": "8.62"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 73.03
      }
    },
    {
      "id": "3-ss-pipe-80-nb",
      "title": "3\" SS pipe (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "od": "88.90"
      },
      "values": {
        "sch10s": {
          "t": "3.05",
          "id": "82.80",
          "m": "6.56"
        },
        "sch40s": {
          "t": "5.49",
          "id": "77.92",
          "m": "11.28"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 88.9
      }
    },
    {
      "id": "3-1-2-ss-pipe-90-nb",
      "title": "3 1/2\" SS pipe (90 NB)",
      "fixed": {
        "nps": "3 1/2\"",
        "dn": "90",
        "od": "101.60"
      },
      "values": {
        "sch10s": {
          "t": "3.05",
          "id": "95.50",
          "m": "7.53"
        },
        "sch40s": {
          "t": "5.74",
          "id": "90.12",
          "m": "13.56"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 101.6
      }
    },
    {
      "id": "4-ss-pipe-100-nb",
      "title": "4\" SS pipe (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "od": "114.30"
      },
      "values": {
        "sch10s": {
          "t": "3.05",
          "id": "108.20",
          "m": "8.50"
        },
        "sch40s": {
          "t": "6.02",
          "id": "102.26",
          "m": "16.06"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 114.3
      }
    },
    {
      "id": "5-ss-pipe-125-nb",
      "title": "5\" SS pipe (125 NB)",
      "fixed": {
        "nps": "5\"",
        "dn": "125",
        "od": "141.30"
      },
      "values": {
        "sch10s": {
          "t": "3.40",
          "id": "134.50",
          "m": "11.74"
        },
        "sch40s": {
          "t": "6.55",
          "id": "128.20",
          "m": "21.76"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 141.3
      }
    },
    {
      "id": "6-ss-pipe-150-nb",
      "title": "6\" SS pipe (150 NB)",
      "fixed": {
        "nps": "6\"",
        "dn": "150",
        "od": "168.28"
      },
      "values": {
        "sch10s": {
          "t": "3.40",
          "id": "161.48",
          "m": "14.04"
        },
        "sch40s": {
          "t": "7.11",
          "id": "154.06",
          "m": "28.23"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 168.28
      }
    },
    {
      "id": "8-ss-pipe-200-nb",
      "title": "8\" SS pipe (200 NB)",
      "fixed": {
        "nps": "8\"",
        "dn": "200",
        "od": "219.08"
      },
      "values": {
        "sch10s": {
          "t": "3.76",
          "id": "211.56",
          "m": "20.33"
        },
        "sch40s": {
          "t": "8.18",
          "id": "202.72",
          "m": "42.49"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 219.08
      }
    },
    {
      "id": "10-ss-pipe-250-nb",
      "title": "10\" SS pipe (250 NB)",
      "fixed": {
        "nps": "10\"",
        "dn": "250",
        "od": "273.05"
      },
      "values": {
        "sch10s": {
          "t": "4.19",
          "id": "264.67",
          "m": "28.29"
        },
        "sch40s": {
          "t": "9.27",
          "id": "254.51",
          "m": "60.24"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 273.05
      }
    },
    {
      "id": "12-ss-pipe-300-nb",
      "title": "12\" SS pipe (300 NB)",
      "fixed": {
        "nps": "12\"",
        "dn": "300",
        "od": "323.85"
      },
      "values": {
        "sch10s": {
          "t": "4.57",
          "id": "314.71",
          "m": "36.63"
        },
        "sch40s": {
          "t": "9.52",
          "id": "304.81",
          "m": "73.76"
        }
      },
      "drawing": {
        "kind": "pipe",
        "od": 323.85
      }
    }
  ]
}
