// GENERATED by scripts/port-piping.ts from Piping_15.html. Do not edit.
import type { CatalogueRow } from '../types'

export const ROWS: Record<string, CatalogueRow[]> = {
  "thr-socket": [
    {
      "id": "socket-bsp-threaded-150-lb-1-8-6-nb",
      "title": "1/8\" (6 NB)",
      "fixed": {
        "nps": "1/8\"",
        "dn": "6",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-1-4-8-nb",
      "title": "1/4\" (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-3-8-10-nb",
      "title": "3/8\" (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-2-1-2-65-nb",
      "title": "2 1/2\" (65 NB)",
      "fixed": {
        "nps": "2 1/2\"",
        "dn": "65",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    },
    {
      "id": "socket-bsp-threaded-150-lb-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Socket BSP threaded 150 lb"
    }
  ],
  "thr-union": [
    {
      "id": "union-cf-bsp-threaded-150-lb-1-4-8-nb",
      "title": "1/4\" (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-3-8-10-nb",
      "title": "3/8\" (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    },
    {
      "id": "union-cf-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "CF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Union cf BSP threaded 150 lb"
    }
  ],
  "thr-nipple": [
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-1-8-6-nb",
      "title": "1/8\" (6 NB)",
      "fixed": {
        "nps": "1/8\"",
        "dn": "6",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-1-4-8-nb",
      "title": "1/4\" (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-3-8-10-nb",
      "title": "3/8\" (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-2-1-2-65-nb",
      "title": "2 1/2\" (65 NB)",
      "fixed": {
        "nps": "2 1/2\"",
        "dn": "65",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-barrel-bsp-threaded-150-lb-4-100-nb",
      "title": "4\" (100 NB)",
      "fixed": {
        "nps": "4\"",
        "dn": "100",
        "pattern": "BARREL"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple barrel BSP threaded 150 lb"
    },
    {
      "id": "nipple-hex-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "HEX"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple hex BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    },
    {
      "id": "nipple-swage-bsp-threaded-150-lb-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "pattern": "SWAGE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Nipple swage BSP threaded 150 lb"
    }
  ],
  "thr-plug": [
    {
      "id": "plug-square-bsp-threaded-150-lb-1-4-8-nb",
      "title": "1/4\" (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-3-8-10-nb",
      "title": "3/8\" (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    },
    {
      "id": "plug-square-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "SQUARE"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Plug square BSP threaded 150 lb"
    }
  ],
  "thr-bush": [
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-4-x-1-8-8-x-6-nb",
      "title": "1/4\" x 1/8\" (8 x 6 NB)",
      "fixed": {
        "nps": "1/4\" x 1/8\"",
        "dn": "8 x 6",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-3-8-x-1-4-10-x-8-nb",
      "title": "3/8\" x 1/4\" (10 x 8 NB)",
      "fixed": {
        "nps": "3/8\" x 1/4\"",
        "dn": "10 x 8",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-2-x-1-4-15-x-8-nb",
      "title": "1/2\" x 1/4\" (15 x 8 NB)",
      "fixed": {
        "nps": "1/2\" x 1/4\"",
        "dn": "15 x 8",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-2-x-3-8-15-x-10-nb",
      "title": "1/2\" x 3/8\" (15 x 10 NB)",
      "fixed": {
        "nps": "1/2\" x 3/8\"",
        "dn": "15 x 10",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-3-4-x-1-4-20-x-8-nb",
      "title": "3/4\" x 1/4\" (20 x 8 NB)",
      "fixed": {
        "nps": "3/4\" x 1/4\"",
        "dn": "20 x 8",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-3-4-x-1-2-20-x-15-nb",
      "title": "3/4\" x 1/2\" (20 x 15 NB)",
      "fixed": {
        "nps": "3/4\" x 1/2\"",
        "dn": "20 x 15",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-x-1-2-25-x-15-nb",
      "title": "1\" x 1/2\" (25 x 15 NB)",
      "fixed": {
        "nps": "1\" x 1/2\"",
        "dn": "25 x 15",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-x-3-4-25-x-20-nb",
      "title": "1\" x 3/4\" (25 x 20 NB)",
      "fixed": {
        "nps": "1\" x 3/4\"",
        "dn": "25 x 20",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-1-4-x-3-4-32-x-20-nb",
      "title": "1 1/4\" x 3/4\" (32 x 20 NB)",
      "fixed": {
        "nps": "1 1/4\" x 3/4\"",
        "dn": "32 x 20",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-1-4-x-1-32-x-25-nb",
      "title": "1 1/4\" x 1\" (32 x 25 NB)",
      "fixed": {
        "nps": "1 1/4\" x 1\"",
        "dn": "32 x 25",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-1-2-x-3-4-40-x-20-nb",
      "title": "1 1/2\" x 3/4\" (40 x 20 NB)",
      "fixed": {
        "nps": "1 1/2\" x 3/4\"",
        "dn": "40 x 20",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-1-2-x-1-40-x-25-nb",
      "title": "1 1/2\" x 1\" (40 x 25 NB)",
      "fixed": {
        "nps": "1 1/2\" x 1\"",
        "dn": "40 x 25",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-1-1-2-x-1-1-4-40-x-32-nb",
      "title": "1 1/2\" x 1 1/4\" (40 x 32 NB)",
      "fixed": {
        "nps": "1 1/2\" x 1 1/4\"",
        "dn": "40 x 32",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-2-x-1-50-x-25-nb",
      "title": "2\" x 1\" (50 x 25 NB)",
      "fixed": {
        "nps": "2\" x 1\"",
        "dn": "50 x 25",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-2-x-1-1-4-50-x-32-nb",
      "title": "2\" x 1 1/4\" (50 x 32 NB)",
      "fixed": {
        "nps": "2\" x 1 1/4\"",
        "dn": "50 x 32",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-2-x-1-1-2-50-x-40-nb",
      "title": "2\" x 1 1/2\" (50 x 40 NB)",
      "fixed": {
        "nps": "2\" x 1 1/2\"",
        "dn": "50 x 40",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-2-1-2-x-2-65-x-50-nb",
      "title": "2 1/2\" x 2\" (65 x 50 NB)",
      "fixed": {
        "nps": "2 1/2\" x 2\"",
        "dn": "65 x 50",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-3-x-2-80-x-50-nb",
      "title": "3\" x 2\" (80 x 50 NB)",
      "fixed": {
        "nps": "3\" x 2\"",
        "dn": "80 x 50",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    },
    {
      "id": "reducing-bush-bsp-threaded-150-lb-3-x-2-1-2-80-x-65-nb",
      "title": "3\" x 2 1/2\" (80 x 65 NB)",
      "fixed": {
        "nps": "3\" x 2 1/2\"",
        "dn": "80 x 65",
        "pattern": "—"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Reducing bush BSP threaded 150 lb"
    }
  ],
  "thr-elbow": [
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-1-4-8-nb",
      "title": "1/4\" (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-3-8-10-nb",
      "title": "3/8\" (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    },
    {
      "id": "elbow-90-ff-bsp-threaded-150-lb-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "pattern": "FF"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Elbow 90° ff BSP threaded 150 lb"
    }
  ],
  "thr-tee": [
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-1-4-8-nb",
      "title": "1/4\" (8 NB)",
      "fixed": {
        "nps": "1/4\"",
        "dn": "8",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-3-8-10-nb",
      "title": "3/8\" (10 NB)",
      "fixed": {
        "nps": "3/8\"",
        "dn": "10",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-1-2-15-nb",
      "title": "1/2\" (15 NB)",
      "fixed": {
        "nps": "1/2\"",
        "dn": "15",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-3-4-20-nb",
      "title": "3/4\" (20 NB)",
      "fixed": {
        "nps": "3/4\"",
        "dn": "20",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-1-25-nb",
      "title": "1\" (25 NB)",
      "fixed": {
        "nps": "1\"",
        "dn": "25",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-1-1-4-32-nb",
      "title": "1 1/4\" (32 NB)",
      "fixed": {
        "nps": "1 1/4\"",
        "dn": "32",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-1-1-2-40-nb",
      "title": "1 1/2\" (40 NB)",
      "fixed": {
        "nps": "1 1/2\"",
        "dn": "40",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-2-50-nb",
      "title": "2\" (50 NB)",
      "fixed": {
        "nps": "2\"",
        "dn": "50",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    },
    {
      "id": "equal-tee-f-bsp-threaded-150-lb-3-80-nb",
      "title": "3\" (80 NB)",
      "fixed": {
        "nps": "3\"",
        "dn": "80",
        "pattern": "F"
      },
      "values": {
        "bsp": {}
      },
      "kind": "Equal tee f BSP threaded 150 lb"
    }
  ]
}
