/**
 * Chat import endpoint.
 *
 * Reads a supplier's file in whatever layout it arrived in and proposes rows in
 * the standard shape of §5. It has no database access and writes nothing — the
 * rows it returns go to the same diff and the same confirmation dialogue as a
 * hand-made CSV.
 *
 * The model API key lives here, in the function's secrets, and never reaches
 * the browser:
 *
 *   supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
 *   supabase functions deploy chat-import
 */

import Anthropic from 'npm:@anthropic-ai/sdk@^0.72.0'
import { zodOutputFormat } from 'npm:@anthropic-ai/sdk@^0.72.0/helpers/zod'
import { z } from 'npm:zod@^3.23.8'

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-client-info',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

const ReplySchema = z.object({
  message: z
    .string()
    .describe('One or two sentences to the user about what you read and anything odd.'),
  interpretation: z.object({
    code: z.string().describe('Which column or field you took the supplier code from.'),
    description: z.string().describe('Which column you took the description from.'),
    unit: z.string().describe('Which column you took the unit from, or how you inferred it.'),
    price: z.string().describe('Which column you took the price from.'),
    notes: z
      .array(z.string())
      .describe('Anything the user should check: skipped pages, VAT basis, odd units.'),
  }),
  rows: z.array(
    z.object({
      code: z.string().describe('Supplier code, trimmed and upper case.'),
      description: z.string(),
      unit: z.string().describe('each, m, length — infer from the document.'),
      price: z
        .number()
        .nullable()
        .describe('Null for price-on-application. Never guess a number.'),
    }),
  ),
})

const SYSTEM = `You read supplier price lists for a mechanical engineering firm and turn them
into rows of a fixed shape: code, description, unit, price.

Rules, in order of importance:

1. Never invent a price. If a line has no price, or says POA / price on application /
   on request, set price to null. A wrong price costs the firm money on a quote; a
   missing one costs nothing.
2. Never invent a code. If a line has no supplier code, leave it out of rows and say so
   in your message.
3. Prefer decoding sizes from the supplier code over the printed size column. Printed
   size cells in these documents are frequently wrong — transposed digits, stray
   characters, and whole columns showing the neighbouring column's values. The code is
   generated by the supplier's system and is reliable.
4. Prices are per the unit stated in the document. Do not convert currencies or units.
5. State your column interpretation plainly in the interpretation field, including which
   pages or sections you skipped and why.

If the user tells you a column is wrong, redo the whole extraction with that correction
applied — do not patch individual rows.

You are proposing rows for a human to review against a diff. You are not writing to any
database, and you should not claim to have done so.`

Deno.serve(async (request: Request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: CORS })
  if (request.method !== 'POST') {
    return new Response('POST only', { status: 405, headers: CORS })
  }

  const apiKey = Deno.env.get('ANTHROPIC_API_KEY')
  if (!apiKey) {
    return new Response(
      JSON.stringify({ error: 'ANTHROPIC_API_KEY is not set on this function.' }),
      { status: 500, headers: { ...CORS, 'Content-Type': 'application/json' } },
    )
  }

  try {
    const body = await request.json()
    const { turns = [], attachment = null, supplierName = '', effectiveFrom = '' } = body

    // The document goes first and is cached, so a correction in conversation
    // re-reads it without paying for it again.
    const opening: unknown[] = []
    if (attachment?.kind === 'pdf') {
      opening.push({
        type: 'document',
        source: { type: 'base64', media_type: 'application/pdf', data: attachment.base64 },
        cache_control: { type: 'ephemeral' },
      })
    } else if (attachment?.kind === 'text') {
      opening.push({
        type: 'text',
        text: `File: ${attachment.name}\n\n${attachment.text}`,
        cache_control: { type: 'ephemeral' },
      })
    }

    opening.push({
      type: 'text',
      text:
        `Supplier: ${supplierName || 'not stated'}. Effective from: ${effectiveFrom || 'not stated'}.\n\n` +
        (turns[0]?.text ?? 'Read this file and give me the price rows.'),
    })

    const messages = [
      { role: 'user', content: opening },
      ...turns.slice(1).map((turn: { role: string; text: string }) => ({
        role: turn.role,
        content: turn.text,
      })),
    ]

    const client = new Anthropic({ apiKey })

    // Streaming, because a full supplier list is a long response and a
    // non-streaming request that size risks an HTTP timeout.
    const stream = client.messages.stream({
      model: 'claude-opus-5',
      max_tokens: 64000,
      system: SYSTEM,
      thinking: { type: 'adaptive' },
      output_config: {
        effort: 'medium',
        format: zodOutputFormat(ReplySchema),
      },
      messages,
    })

    const final = await stream.finalMessage()

    if (final.stop_reason === 'refusal') {
      return new Response(
        JSON.stringify({ error: 'The model declined to read this file.' }),
        { status: 422, headers: { ...CORS, 'Content-Type': 'application/json' } },
      )
    }

    const text = final.content
      .filter((block): block is { type: 'text'; text: string } => block.type === 'text')
      .map((block) => block.text)
      .join('')

    const parsed = ReplySchema.parse(JSON.parse(text))

    // Normalise here so the client gets exactly the standard shape.
    const rows = parsed.rows
      .map((row) => ({
        code: row.code.trim().toUpperCase(),
        description: row.description.trim(),
        unit: row.unit.trim(),
        price: row.price === null ? null : Math.round(row.price * 100) / 100,
      }))
      .filter((row) => row.code !== '')

    return new Response(
      JSON.stringify({ message: parsed.message, interpretation: parsed.interpretation, rows }),
      { headers: { ...CORS, 'Content-Type': 'application/json' } },
    )
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause)
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    })
  }
})
