/**
 * Chat import endpoint.
 *
 * Reads a supplier's file in whatever layout it arrived in and proposes rows in
 * the standard shape of §5. It has no database access and writes nothing — the
 * rows it returns go to the same diff and the same confirmation dialogue as a
 * hand-made CSV.
 *
 * The model API key lives here, in the function's secrets, and never reaches
 * the browser:
 *
 *   supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
 *   supabase secrets set ALLOWED_ORIGINS=https://<the deployed app>
 *   supabase functions deploy chat-import
 */

import Anthropic from 'npm:@anthropic-ai/sdk@^0.72.0'
import { zodOutputFormat } from 'npm:@anthropic-ai/sdk@^0.72.0/helpers/zod'
import { z } from 'npm:zod@^3.23.8'

/**
 * Which sites may call this function.
 *
 *   supabase secrets set ALLOWED_ORIGINS=https://pafd.onrender.com
 *
 * Comma-separated if the app is reachable at more than one address. Left
 * unset, only local development is allowed — that is the safe default,
 * because every call to this endpoint spends money at the model API, and a
 * wildcard would let any page on the internet spend it.
 */
const ALLOWED_ORIGINS = (Deno.env.get('ALLOWED_ORIGINS') ?? 'http://localhost:3000')
  .split(',')
  .map((origin) => origin.trim())
  .filter((origin) => origin !== '')

function corsFor(origin: string | null): Record<string, string> {
  const headers: Record<string, string> = {
    'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-client-info',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    // The allowed origin varies per request, so caches must key on it.
    Vary: 'Origin',
  }
  if (origin !== null && ALLOWED_ORIGINS.includes(origin)) {
    headers['Access-Control-Allow-Origin'] = origin
  }
  return headers
}

/**
 * A browser always sends `Origin` on a cross-site POST, so the allow-list
 * stops another site from spending the firm's model credit. A caller with no
 * `Origin` at all — curl, or the app's own server — is let through; what
 * stands in front of those is the project key the platform checks before the
 * request ever reaches this code.
 */
function isAllowed(origin: string | null): boolean {
  return origin === null || ALLOWED_ORIGINS.includes(origin)
}

function json(body: unknown, status: number, cors: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  })
}

const ReplySchema = z.object({
  message: z
    .string()
    .describe('One or two sentences to the user about what you read and anything odd.'),
  interpretation: z.object({
    code: z.string().describe('Which column or field you took the supplier code from.'),
    description: z.string().describe('Which column you took the description from.'),
    unit: z.string().describe('Which column you took the unit from, or how you inferred it.'),
    price: z.string().describe('Which column you took the price from.'),
    notes: z
      .array(z.string())
      .describe('Anything the user should check: skipped pages, VAT basis, odd units.'),
  }),
  rows: z.array(
    z.object({
      code: z.string().describe('Supplier code, trimmed and upper case.'),
      description: z.string(),
      unit: z.string().describe('each, m, length — infer from the document.'),
      price: z
        .number()
        .nullable()
        .describe('Null for price-on-application. Never guess a number.'),
    }),
  ),
})

const SYSTEM = `You read supplier price lists for a mechanical engineering firm and turn them
into rows of a fixed shape: code, description, unit, price.

Rules, in order of importance:

1. Never invent a price. If a line has no price, or says POA / price on application /
   on request, set price to null. A wrong price costs the firm money on a quote; a
   missing one costs nothing.
2. Never invent a code. If a line has no supplier code, leave it out of rows and say so
   in your message.
3. Prefer decoding sizes from the supplier code over the printed size column. Printed
   size cells in these documents are frequently wrong — transposed digits, stray
   characters, and whole columns showing the neighbouring column's values. The code is
   generated by the supplier's system and is reliable.
4. Prices are per the unit stated in the document. Do not convert currencies or units.
5. State your column interpretation plainly in the interpretation field, including which
   pages or sections you skipped and why.

If the user tells you a column is wrong, redo the whole extraction with that correction
applied — do not patch individual rows.

You are proposing rows for a human to review against a diff. You are not writing to any
database, and you should not claim to have done so.`

Deno.serve(async (request: Request) => {
  const origin = request.headers.get('Origin')
  const cors = corsFor(origin)

  if (request.method === 'OPTIONS') return new Response('ok', { headers: cors })
  if (request.method !== 'POST') {
    return new Response('POST only', { status: 405, headers: cors })
  }

  if (!isAllowed(origin)) {
    // No allow-origin header goes back with this, so the browser hides the
    // body from the page that asked. The readable version is in the function
    // logs, which is where whoever set ALLOWED_ORIGINS will be looking.
    console.error(`Refused a call from ${origin}; ALLOWED_ORIGINS is ${ALLOWED_ORIGINS.join(', ')}`)
    return json({ error: `This function does not accept calls from ${origin}.` }, 403, cors)
  }

  const apiKey = Deno.env.get('ANTHROPIC_API_KEY')
  if (!apiKey) {
    return json({ error: 'ANTHROPIC_API_KEY is not set on this function.' }, 500, cors)
  }

  try {
    const body = await request.json()
    const { turns = [], attachment = null, supplierName = '', effectiveFrom = '' } = body

    // The document goes first and is cached, so a correction in conversation
    // re-reads it without paying for it again.
    const opening: unknown[] = []
    if (attachment?.kind === 'pdf') {
      opening.push({
        type: 'document',
        source: { type: 'base64', media_type: 'application/pdf', data: attachment.base64 },
        cache_control: { type: 'ephemeral' },
      })
    } else if (attachment?.kind === 'text') {
      opening.push({
        type: 'text',
        text: `File: ${attachment.name}\n\n${attachment.text}`,
        cache_control: { type: 'ephemeral' },
      })
    }

    opening.push({
      type: 'text',
      text:
        `Supplier: ${supplierName || 'not stated'}. Effective from: ${effectiveFrom || 'not stated'}.\n\n` +
        (turns[0]?.text ?? 'Read this file and give me the price rows.'),
    })

    const messages = [
      { role: 'user', content: opening },
      ...turns.slice(1).map((turn: { role: string; text: string }) => ({
        role: turn.role,
        content: turn.text,
      })),
    ]

    const client = new Anthropic({ apiKey })

    // Streaming, because a full supplier list is a long response and a
    // non-streaming request that size risks an HTTP timeout.
    const stream = client.messages.stream({
      model: 'claude-opus-5',
      max_tokens: 128000,
      system: SYSTEM,
      thinking: { type: 'adaptive' },
      output_config: {
        effort: 'medium',
        format: zodOutputFormat(ReplySchema),
      },
      messages,
    })

    const final = await stream.finalMessage()

    if (final.stop_reason === 'refusal') {
      return json({ error: 'The model declined to read this file.' }, 422, cors)
    }

    if (final.stop_reason === 'max_tokens') {
      // The reply is one JSON document, so a cut-off response is not a short
      // list — it is an unreadable one. Say that, rather than letting it fail
      // later as a parse error that reads like a bug.
      return json(
        {
          error:
            'That list was too long to come back in one piece — it was cut off mid-row, ' +
            'so none of it can be used. Split the file and import it in parts.',
        },
        413,
        cors,
      )
    }

    const text = final.content
      .filter((block): block is { type: 'text'; text: string } => block.type === 'text')
      .map((block) => block.text)
      .join('')

    let parsed: z.infer<typeof ReplySchema>
    try {
      parsed = ReplySchema.parse(JSON.parse(text))
    } catch (cause) {
      console.error('Unreadable reply from the model:', cause, text.slice(0, 2_000))
      return json(
        { error: 'The model returned something this function could not read as price rows.' },
        502,
        cors,
      )
    }

    // Normalise here so the client gets exactly the standard shape.
    const rows = parsed.rows
      .map((row) => ({
        code: row.code.trim().toUpperCase(),
        description: row.description.trim(),
        unit: row.unit.trim(),
        price: row.price === null ? null : Math.round(row.price * 100) / 100,
      }))
      .filter((row) => row.code !== '')

    return json(
      { message: parsed.message, interpretation: parsed.interpretation, rows },
      200,
      cors,
    )
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause)
    return json({ error: message }, 500, cors)
  }
})
